### PR TITLE
fix crash, dbus call

### LINKED ISSUE #1: bt-device -c crashes after entering passkey
# bt-device -c 5C:0E:8B:03:6E:4E
Connecting to: 5C:0E:8B:03:6E:4E
Device: CS3070:10172522500886 (5C:0E:8B:03:6E:4E)
Enter passkey: 1234
Segmentation fault

Debugging with gdb reveals the following backtrace

#0  0xb6e77d00 in g_utf8_validate () from /usr/lib/libglib-2.0.so.0
#1  0xb6e7b5c8 in g_variant_new_string () from /usr/lib/libglib-2.0.so.0
#2  0x0000c0b8 in _bt_agent_method_call_func (connection=<optimized out>,
    sender=<optimized out>, object_path=<optimized out>,
    interface_name=<optimized out>, method_name=0x18fc228 "RequestPinCode",
    parameters=0x1905f00, invocation=0x18fdab0, user_data=0x0)
    at lib/agent-helper.c:310

Analyzing line 310 in lib/agent-helper.c indicates a possible cause, passkey is being read into an uninitialized gchar pointer

### PR DESCRIPTION
**Pull request by syntheticpp**
fixes #1 and a dbus error with bluez5

### CODE REVIEW

**Comment by gitjackolantern** [comment]
Hmm, interesting. Will examine and update this week. Need to read and review.

**Comment by syntheticpp** [comment]
I've used BLuz5 5.33. glib (g_) complains it expects a '(s)' but got a 's', but the BlueZ doc only lists a string, and your introspection code also only lists 's', so I wonder if it is a glib bug. Or is it a design design of the dbus binding to always expect a variable tuple?

**Comment by gitjackolantern** [comment]
Looks fine at a glance :) Thanks for the fix.

**Comment by syntheticpp** [comment]
In meantime I saw, that the GVariant part of the patch is also needed in line 271 (the case RequestPasskey).
When I see now fix from you I'll will push another patch in next time.

**Pull request merged**
